# Generated by Django 3.1.6 on 2021-03-05 11:33

import colorfield.fields
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pastvina.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='jméno')),
                ('name_genitive', models.CharField(max_length=30, verbose_name='jméno (druhý pád)')),
                ('base_price_buy', models.FloatField(verbose_name='základní nákupní cena')),
                ('base_price_sell', models.FloatField(verbose_name='základní prodejní cena')),
                ('growth_time', models.IntegerField(verbose_name='čas růstu')),
                ('rotting_time', models.IntegerField(verbose_name='čas kažení')),
                ('feed_value', models.FloatField(verbose_name='výživová hodnota')),
                ('color', colorfield.fields.ColorField(default='#aaaaaa', max_length=18, verbose_name='barva')),
            ],
            options={
                'verbose_name': 'plodina',
                'verbose_name_plural': 'plodiny',
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='jméno')),
                ('name_genitive', models.CharField(max_length=30, verbose_name='jméno (druhý pád)')),
                ('base_price_buy', models.FloatField(verbose_name='základní nákupní cena')),
                ('base_price_sell', models.FloatField(verbose_name='základní prodejní cena')),
                ('growth_time', models.IntegerField(verbose_name='čas růstu')),
                ('consumption', models.FloatField(verbose_name='spotřeba')),
                ('color', colorfield.fields.ColorField(default='#aaaaaa', max_length=18, verbose_name='barva')),
            ],
            options={
                'verbose_name': 'dobytek',
                'verbose_name_plural': 'dobytek',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='vytvořeno')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='upraveno')),
                ('endpoint', models.CharField(max_length=30, verbose_name='URL lokace')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('name', models.CharField(max_length=30, verbose_name='název v menu')),
                ('content', models.TextField(verbose_name='obsah')),
            ],
            options={
                'verbose_name': 'statická stránka',
                'verbose_name_plural': 'statické stránky',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='jméno')),
                ('locations', models.TextField(verbose_name='lokace')),
                ('pages', models.ManyToManyField(to='pastvina.StaticPage')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='vytvořeno')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='upraveno')),
                ('public', models.BooleanField(verbose_name='veřejné')),
                ('content', models.FileField(storage=django.core.files.storage.FileSystemStorage('/home/apophis/jan/souteze/ntrophy/2021/logika-2021-pastvina/pastvina/storage', '/'), upload_to=pastvina.models.MediaFile.path_in_storage, verbose_name='soubor')),
                ('name', models.SlugField(max_length=60, unique=True, verbose_name='jméno')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='vlastník')),
            ],
            options={
                'verbose_name': 'soubor',
                'verbose_name_plural': 'soubory',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='vytvořeno')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='upraveno')),
                ('published', models.BooleanField(blank=True, default=False, verbose_name='publikováno')),
                ('public_from', models.DateTimeField(blank=True, null=True, verbose_name='publikováno od')),
                ('public_to', models.DateTimeField(blank=True, null=True, verbose_name='publikováno do')),
                ('name', models.CharField(max_length=60, verbose_name='název')),
                ('text', models.TextField(verbose_name='text novinky')),
                ('tags', models.TextField(blank=True, default='', verbose_name='tagy')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'novinka',
                'verbose_name_plural': 'novinky',
            },
        ),
    ]
