# Generated by Django 3.1.6 on 2021-03-06 09:17

import colorfield.fields
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pastvina.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='jméno')),
                ('name_genitive', models.CharField(max_length=30, verbose_name='jméno (druhý pád)')),
                ('base_price_buy', models.IntegerField(verbose_name='základní nákupní cena')),
                ('base_price_sell', models.IntegerField(verbose_name='základní prodejní cena')),
                ('growth_time', models.IntegerField(verbose_name='čas růstu')),
                ('rotting_time', models.IntegerField(verbose_name='čas kažení')),
                ('color', colorfield.fields.ColorField(default='#aaaaaa', max_length=18, verbose_name='barva')),
            ],
            options={
                'verbose_name': 'plodina',
                'verbose_name_plural': 'plodiny',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='start')),
                ('ticks', models.IntegerField(verbose_name='počet minikol')),
                ('period', models.TimeField(verbose_name='délka minikola')),
                ('crop_storage_size', models.IntegerField(verbose_name='velikost skladu')),
                ('livestock_slaughter_limit', models.IntegerField(verbose_name='limit porážení')),
                ('start_money', models.PositiveIntegerField(verbose_name='počáteční peníze')),
            ],
            options={
                'verbose_name': 'hra',
                'verbose_name_plural': 'hry',
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='jméno')),
                ('name_genitive', models.CharField(max_length=30, verbose_name='jméno (druhý pád)')),
                ('base_price_buy', models.IntegerField(verbose_name='základní nákupní cena')),
                ('base_price_sell', models.IntegerField(verbose_name='základní prodejní cena')),
                ('product_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='jméno produktu')),
                ('product_name_genitive', models.CharField(blank=True, max_length=30, null=True, verbose_name='jméno produktu (druhý pád)')),
                ('product_price', models.IntegerField(verbose_name='základní cena produktu')),
                ('growth_time', models.IntegerField(verbose_name='čas růstu')),
                ('consumption', models.FloatField(verbose_name='spotřeba')),
                ('color', colorfield.fields.ColorField(default='#aaaaaa', max_length=18, verbose_name='barva')),
                ('consumption_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='krmivo')),
            ],
            options={
                'verbose_name': 'dobytek',
                'verbose_name_plural': 'dobytek',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='vytvořeno')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='upraveno')),
                ('published', models.BooleanField(blank=True, default=False, verbose_name='publikováno')),
                ('public_from', models.DateTimeField(blank=True, null=True, verbose_name='publikováno od')),
                ('public_to', models.DateTimeField(blank=True, null=True, verbose_name='publikováno do')),
                ('name', models.CharField(max_length=60, verbose_name='název')),
                ('text', models.TextField(verbose_name='text novinky')),
                ('tags', models.TextField(blank=True, default='', verbose_name='tagy')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'novinka',
                'verbose_name_plural': 'novinky',
            },
        ),
        migrations.CreateModel(
            name='TeamLivestockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(verbose_name='číslo minikola')),
                ('age', models.IntegerField(verbose_name='stáří dobytka')),
                ('amount', models.IntegerField(verbose_name='množství')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='dobytek')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým')),
            ],
            options={
                'verbose_name': 'historie herních parametrů týmu (dobytek)',
                'verbose_name_plural': 'historie herních parametrů týmů (dobytek)',
                'unique_together': {('round', 'user', 'tick', 'livestock', 'age')},
            },
        ),
        migrations.CreateModel(
            name='TeamHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(verbose_name='číslo minikola')),
                ('money', models.IntegerField(verbose_name='peníze')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým')),
            ],
            options={
                'verbose_name': 'historie herních parametrů týmu',
                'verbose_name_plural': 'historie herních parametrů týmů',
                'unique_together': {('round', 'user', 'tick')},
            },
        ),
        migrations.CreateModel(
            name='TeamCropHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(verbose_name='číslo minikola')),
                ('age', models.IntegerField(verbose_name='stáří produktu')),
                ('amount', models.IntegerField(verbose_name='množství')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='plodina')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým')),
            ],
            options={
                'verbose_name': 'historie herních parametrů týmu (plodiny)',
                'verbose_name_plural': 'historie herních parametrů týmů (plodiny)',
                'unique_together': {('round', 'user', 'tick', 'crop', 'age')},
            },
        ),
        migrations.CreateModel(
            name='LivestockMarketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(verbose_name='číslo minikola')),
                ('amount_sold', models.PositiveIntegerField(verbose_name='prodané množství')),
                ('current_price_buy', models.PositiveIntegerField(verbose_name='nákupní cena')),
                ('current_price_sell', models.PositiveIntegerField(verbose_name='prodejní cena')),
                ('product_amount_sold', models.PositiveIntegerField(verbose_name='prodané množství')),
                ('product_current_price', models.PositiveIntegerField(verbose_name='aktuální cena')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='dobytek')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo')),
            ],
            options={
                'verbose_name': 'historie obchodu (dobytek)',
                'verbose_name_plural': 'hisotire obchodů (dobytek)',
                'unique_together': {('round', 'tick', 'livestock')},
            },
        ),
        migrations.CreateModel(
            name='CropMarketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(verbose_name='číslo minikola')),
                ('amount_sold', models.PositiveIntegerField(verbose_name='prodané množství')),
                ('current_price_buy', models.PositiveIntegerField(verbose_name='nákupní cena')),
                ('current_price_sell', models.PositiveIntegerField(verbose_name='prodejní cena')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='plodina')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo')),
            ],
            options={
                'verbose_name': 'historie obchodu (plodiny)',
                'verbose_name_plural': 'historie obchodů (plodiny)',
                'unique_together': {('round', 'tick', 'crop')},
            },
        ),
    ]
