# Generated by Django 3.1.6 on 2021-03-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'verbose_name': 'kolo', 'verbose_name_plural': 'kola'},
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='round',
            name='start',
            field=models.DateTimeField(verbose_name='start'),
        ),
    ]
