# Generated by Django 3.1.6 on 2021-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='period',
            field=models.IntegerField(verbose_name='délka minikola v 10s'),
        ),
    ]
