# Generated by Django 3.1.6 on 2021-03-05 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastvina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='auth.user', verbose_name='tým')),
                ('money', models.IntegerField(verbose_name='peníze')),
            ],
            options={
                'verbose_name': 'herní parametry týmu',
                'verbose_name_plural': 'herní parametry týmu',
            },
        ),
        migrations.CreateModel(
            name='Grassland',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='jméno')),
            ],
            options={
                'verbose_name': 'pastvina',
                'verbose_name_plural': 'pastviny',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='start')),
            ],
            options={
                'verbose_name': 'kolo',
                'verbose_name_plural': 'kola',
            },
        ),
        migrations.AlterField(
            model_name='livestock',
            name='base_price_buy',
            field=models.IntegerField(verbose_name='základní nákupní cena'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='base_price_sell',
            field=models.IntegerField(verbose_name='základní prodejní cena'),
        ),
        migrations.CreateModel(
            name='RoundLivestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_buy', models.IntegerField(verbose_name='nákupní cena')),
                ('price_sell', models.IntegerField(verbose_name='prodejní cena')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.livestock', verbose_name='dobytek')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým')),
            ],
            options={
                'verbose_name': 'kolo:dobytek',
                'verbose_name_plural': 'kola:dobytek',
                'unique_together': {('user', 'round', 'livestock')},
            },
        ),
        migrations.CreateModel(
            name='RoundGrassland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grassland', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.grassland', verbose_name='pastvina')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým')),
            ],
            options={
                'verbose_name': 'kolo:pastvina',
                'verbose_name_plural': 'kola:pastviny',
                'unique_together': {('user', 'round', 'grassland')},
            },
        ),
        migrations.CreateModel(
            name='RoundCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_buy', models.IntegerField(verbose_name='nákupní cena')),
                ('price_sell', models.IntegerField(verbose_name='prodejní cena')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='plodina')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým')),
            ],
            options={
                'verbose_name': 'kolo:plodina',
                'verbose_name_plural': 'kola:plodiny',
                'unique_together': {('user', 'round', 'crop')},
            },
        ),
    ]
