# Generated by Django 3.1.6 on 2021-03-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0002_auto_20210306_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlivestockhistory',
            name='slaughtered',
            field=models.PositiveIntegerField(default=0, verbose_name='poraženo zvířat'),
        ),
        migrations.AlterField(
            model_name='teamcrophistory',
            name='age',
            field=models.IntegerField(verbose_name='čas do zkažení produktu'),
        ),
        migrations.AlterField(
            model_name='teamlivestockhistory',
            name='age',
            field=models.IntegerField(verbose_name='čas do smrti dobytka'),
        ),
        migrations.AlterField(
            model_name='teamlivestockhistory',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='množství'),
        ),
    ]
