# Generated by Django 3.1.6 on 2021-03-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0002_auto_20210306_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='life_time',
            field=models.IntegerField(default=100, verbose_name='čas života'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.livestock', verbose_name='dobytek'),
        ),
    ]
