# Generated by Django 3.1.6 on 2021-03-06 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastvina', '0002_auto_20210305_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropMarketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(verbose_name='číslo minikola')),
                ('amount_sold', models.PositiveIntegerField(verbose_name='prodané množství')),
                ('current_price', models.PositiveIntegerField(verbose_name='aktuální cena')),
            ],
            options={
                'verbose_name': 'historie obchodu (plodiny)',
                'verbose_name_plural': 'historie obchodů (plodiny)',
            },
        ),
        migrations.CreateModel(
            name='LivestockMarketHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(verbose_name='číslo minikola')),
                ('amount_sold', models.PositiveIntegerField(verbose_name='prodané množství')),
                ('current_price', models.PositiveIntegerField(verbose_name='aktuální cena')),
                ('product_amount_sold', models.PositiveIntegerField(verbose_name='prodané množství')),
                ('product_current_price', models.PositiveIntegerField(verbose_name='aktuální cena')),
            ],
            options={
                'verbose_name': 'historie obchodu (dobytek)',
                'verbose_name_plural': 'hisotire obchodů (dobytek)',
            },
        ),
        migrations.CreateModel(
            name='TeamCropHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(verbose_name='číslo minikola')),
                ('age', models.IntegerField(verbose_name='stáří produktu')),
                ('amount', models.IntegerField(verbose_name='množství')),
            ],
            options={
                'verbose_name': 'historie herních parametrů týmu (plodiny)',
                'verbose_name_plural': 'historie herních parametrů týmů (plodiny)',
            },
        ),
        migrations.CreateModel(
            name='TeamHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(verbose_name='číslo minikola')),
                ('money', models.IntegerField(verbose_name='peníze')),
            ],
            options={
                'verbose_name': 'historie herních parametrů týmu',
                'verbose_name_plural': 'historie herních parametrů týmů',
            },
        ),
        migrations.CreateModel(
            name='TeamLivestockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField(verbose_name='číslo minikola')),
                ('age', models.IntegerField(verbose_name='stáří dobytka')),
                ('amount', models.IntegerField(verbose_name='množství')),
            ],
            options={
                'verbose_name': 'historie herních parametrů týmu (dobytek)',
                'verbose_name_plural': 'historie herních parametrů týmů (dobytek)',
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='pages',
        ),
        migrations.AlterUniqueTogether(
            name='roundcrop',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roundcrop',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='roundcrop',
            name='round',
        ),
        migrations.RemoveField(
            model_name='roundcrop',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='roundgrassland',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roundgrassland',
            name='grassland',
        ),
        migrations.RemoveField(
            model_name='roundgrassland',
            name='round',
        ),
        migrations.RemoveField(
            model_name='roundgrassland',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='roundlivestock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='roundlivestock',
            name='livestock',
        ),
        migrations.RemoveField(
            model_name='roundlivestock',
            name='round',
        ),
        migrations.RemoveField(
            model_name='roundlivestock',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'verbose_name': 'hra', 'verbose_name_plural': 'hry'},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='feed_value',
        ),
        migrations.AddField(
            model_name='livestock',
            name='consumption_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='krmivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestock',
            name='product_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='jméno produktu'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='product_name_genitive',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='jméno produktu (druhý pád)'),
        ),
        migrations.AddField(
            model_name='livestock',
            name='product_price',
            field=models.IntegerField(default=100, verbose_name='základní cena produktu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='crop_storage_size',
            field=models.IntegerField(default=50, verbose_name='velikost skladu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='livestock_slaughter_limit',
            field=models.IntegerField(default=20, verbose_name='limit porážení'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='period',
            field=models.TimeField(default=30, verbose_name='délka minikola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='start_money',
            field=models.PositiveIntegerField(default=1000, verbose_name='počáteční peníze'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='ticks',
            field=models.IntegerField(default=20, verbose_name='počet minikol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='base_price_buy',
            field=models.IntegerField(verbose_name='základní nákupní cena'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='base_price_sell',
            field=models.IntegerField(verbose_name='základní prodejní cena'),
        ),
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='GameTeam',
        ),
        migrations.DeleteModel(
            name='Grassland',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='RoundCrop',
        ),
        migrations.DeleteModel(
            name='RoundGrassland',
        ),
        migrations.DeleteModel(
            name='RoundLivestock',
        ),
        migrations.DeleteModel(
            name='StaticPage',
        ),
        migrations.AddField(
            model_name='teamlivestockhistory',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='dobytek'),
        ),
        migrations.AddField(
            model_name='teamlivestockhistory',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo'),
        ),
        migrations.AddField(
            model_name='teamlivestockhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým'),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo'),
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým'),
        ),
        migrations.AddField(
            model_name='teamcrophistory',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='plodina'),
        ),
        migrations.AddField(
            model_name='teamcrophistory',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo'),
        ),
        migrations.AddField(
            model_name='teamcrophistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým'),
        ),
        migrations.AddField(
            model_name='livestockmarkethistory',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='dobytek'),
        ),
        migrations.AddField(
            model_name='livestockmarkethistory',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo'),
        ),
        migrations.AddField(
            model_name='cropmarkethistory',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='plodina'),
        ),
        migrations.AddField(
            model_name='cropmarkethistory',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo'),
        ),
        migrations.AlterUniqueTogether(
            name='teamlivestockhistory',
            unique_together={('round', 'user', 'tick', 'livestock', 'age')},
        ),
        migrations.AlterUniqueTogether(
            name='teamhistory',
            unique_together={('round', 'user', 'tick')},
        ),
        migrations.AlterUniqueTogether(
            name='teamcrophistory',
            unique_together={('round', 'user', 'tick', 'crop', 'age')},
        ),
        migrations.AlterUniqueTogether(
            name='livestockmarkethistory',
            unique_together={('round', 'tick', 'livestock')},
        ),
        migrations.AlterUniqueTogether(
            name='cropmarkethistory',
            unique_together={('round', 'tick', 'crop')},
        ),
    ]
