# Generated by Django 3.1.6 on 2021-03-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0003_auto_20210306_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='public_to',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='updated',
        ),
    ]
