# Generated by Django 3.1.6 on 2021-03-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0003_auto_20210306_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropmarkethistory',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='livestockmarkethistory',
            name='current_price',
        ),
        migrations.AddField(
            model_name='cropmarkethistory',
            name='current_price_buy',
            field=models.PositiveIntegerField(default=20, verbose_name='nákupní cena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cropmarkethistory',
            name='current_price_sell',
            field=models.PositiveIntegerField(default=20, verbose_name='prodejní cena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockmarkethistory',
            name='current_price_buy',
            field=models.PositiveIntegerField(default=20, verbose_name='nákupní cena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockmarkethistory',
            name='current_price_sell',
            field=models.PositiveIntegerField(default=20, verbose_name='prodejní cena'),
            preserve_default=False,
        ),
    ]
