# Generated by Django 3.1.6 on 2021-03-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0003_auto_20210307_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamlivestockhistory',
            name='slaughtered',
        ),
        migrations.AddField(
            model_name='teamhistory',
            name='slaughtered',
            field=models.PositiveIntegerField(default=0, verbose_name='poraženo zvířat'),
        ),
    ]
