# Generated by Django 3.1.6 on 2021-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0004_auto_20210307_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmarkethistory',
            name='amount_sold',
            field=models.IntegerField(verbose_name='prodané množství'),
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='amount_sold',
            field=models.IntegerField(verbose_name='prodané množství zvířete'),
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='product_amount_sold',
            field=models.IntegerField(verbose_name='prodané množství produktu'),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='slaughtered',
            field=models.PositiveIntegerField(default=0, verbose_name='prodáno zvířat'),
        ),
    ]
