# Generated by Django 3.1.6 on 2021-03-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0004_auto_20210306_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestockmarkethistory',
            options={'verbose_name': 'historie obchodu (dobytek)', 'verbose_name_plural': 'historie obchodů (dobytek)'},
        ),
        migrations.AlterField(
            model_name='crop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cropmarkethistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='amount_sold',
            field=models.PositiveIntegerField(verbose_name='prodané množství zvířete'),
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='current_price_buy',
            field=models.PositiveIntegerField(verbose_name='nákupní cena zvířete'),
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='current_price_sell',
            field=models.PositiveIntegerField(verbose_name='prodejní cena zvířete'),
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='product_amount_sold',
            field=models.PositiveIntegerField(verbose_name='prodané množství produktu'),
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='product_current_price',
            field=models.PositiveIntegerField(verbose_name='aktuální cena produktu'),
        ),
        migrations.AlterField(
            model_name='teamcrophistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamlivestockhistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teamlivestockhistory',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.livestock', verbose_name='dobytek'),
        ),
    ]
