# Generated by Django 3.1.6 on 2021-03-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0005_auto_20210306_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField(verbose_name='index')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.round', verbose_name='kolo')),
            ],
            options={
                'verbose_name': 'ticks',
                'unique_together': {('round', 'index')},
            },
        ),
    ]
