# Generated by Django 3.1.6 on 2021-03-14 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0006_auto_20210313_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='public_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='veřejné od'),
        ),
    ]
