# Generated by Django 3.1.6 on 2021-03-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0007_auto_20210314_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamhistory',
            name='total_consumption',
            field=models.PositiveIntegerField(default=0, verbose_name='celková spotřeba zvířat'),
            preserve_default=False,
        ),
    ]
