# Generated by Django 3.1.6 on 2021-03-14 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0007_auto_20210314_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='growth_time',
            field=models.PositiveIntegerField(verbose_name='čas růstu'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='rotting_time',
            field=models.PositiveIntegerField(verbose_name='čas kažení'),
        ),
        migrations.AlterField(
            model_name='cropmarkethistory',
            name='amount_sold',
            field=models.IntegerField(default=0, verbose_name='prodané množství'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='consumption',
            field=models.PositiveIntegerField(verbose_name='spotřeba'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='growth_time',
            field=models.PositiveIntegerField(verbose_name='čas růstu'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='life_time',
            field=models.PositiveIntegerField(verbose_name='čas života'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='product_name',
            field=models.CharField(default='', max_length=30, verbose_name='jméno produktu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestock',
            name='product_name_genitive',
            field=models.CharField(default='', max_length=30, verbose_name='jméno produktu (druhý pád)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='amount_sold',
            field=models.IntegerField(default=0, verbose_name='prodané množství zvířete'),
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='product_amount_sold',
            field=models.IntegerField(default=0, verbose_name='prodané množství produktu'),
        ),
        migrations.AlterField(
            model_name='round',
            name='crop_storage_size',
            field=models.PositiveIntegerField(verbose_name='velikost skladu'),
        ),
        migrations.AlterField(
            model_name='round',
            name='livestock_slaughter_limit',
            field=models.PositiveIntegerField(verbose_name='limit porážení'),
        ),
        migrations.AlterField(
            model_name='round',
            name='period',
            field=models.PositiveIntegerField(verbose_name='délka minikola v 10s'),
        ),
        migrations.AlterField(
            model_name='round',
            name='ticks',
            field=models.PositiveIntegerField(verbose_name='počet minikol'),
        ),
        migrations.AlterField(
            model_name='teamcrophistory',
            name='age',
            field=models.PositiveIntegerField(verbose_name='čas do zkažení produktu'),
        ),
        migrations.AlterField(
            model_name='teamcrophistory',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='množství'),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='money',
            field=models.PositiveIntegerField(verbose_name='peníze'),
        ),
        migrations.AlterField(
            model_name='teamlivestockhistory',
            name='age',
            field=models.PositiveIntegerField(verbose_name='čas do smrti dobytka'),
        ),
        migrations.AlterField(
            model_name='teamlivestockhistory',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='množství'),
        ),
        migrations.AlterField(
            model_name='tick',
            name='index',
            field=models.PositiveIntegerField(verbose_name='index'),
        ),
        migrations.AlterField(
            model_name='tick',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start'),
        ),
    ]
