# Generated by Django 3.1.6 on 2021-03-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0008_teamhistory_total_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamhistory',
            name='stock_size',
            field=models.PositiveIntegerField(default=0, verbose_name='velikost zásob'),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='total_consumption',
            field=models.PositiveIntegerField(default=0, verbose_name='celková spotřeba zvířat'),
        ),
    ]
