# Generated by Django 3.1.6 on 2021-03-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0009_auto_20210314_0914'),
        ('pastvina', '0008_auto_20210314_1042'),
    ]

    operations = [
    ]
