# Generated by Django 3.1.6 on 2021-03-14 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastvina', '0010_merge_20210314_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropmarkethistory',
            options={'verbose_name': 'plodiny - historie obchodu', 'verbose_name_plural': 'plodiny - historie obchodů'},
        ),
        migrations.AlterModelOptions(
            name='livestockmarkethistory',
            options={'verbose_name': 'dobytek - historie obchodu', 'verbose_name_plural': 'dobytek - historie obchodů'},
        ),
        migrations.AlterModelOptions(
            name='teamcrophistory',
            options={'verbose_name': 'plodiny - historie množství týmu podle stáří', 'verbose_name_plural': 'plodiny - historie množství týmů podle stáří'},
        ),
        migrations.AlterModelOptions(
            name='teamlivestockhistory',
            options={'verbose_name': 'dobytek - historie množství týmu podle stáří', 'verbose_name_plural': 'dobytek - historie množství týmů podle stáří'},
        ),
        migrations.CreateModel(
            name='TeamLivestockActionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bought', models.PositiveIntegerField(default=0, verbose_name='koupeno')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='prodáno')),
                ('killed', models.PositiveIntegerField(default=0, verbose_name='zabito')),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.livestock', verbose_name='dobytek')),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastvina.tick', verbose_name='minikolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým')),
            ],
            options={
                'verbose_name': 'dobytek - historie akcí týmu',
                'verbose_name_plural': 'dobytek - historie akcí týmů',
                'unique_together': {('tick', 'user', 'livestock')},
            },
        ),
        migrations.CreateModel(
            name='TeamCropActionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bought', models.PositiveIntegerField(default=0, verbose_name='koupeno')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='množství')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pastvina.crop', verbose_name='plodina')),
                ('tick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastvina.tick', verbose_name='minikolo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='tým')),
            ],
            options={
                'verbose_name': 'plodiny - historie akcí týmu',
                'verbose_name_plural': 'plodiny - historie akcí týmů',
                'unique_together': {('tick', 'user', 'crop')},
            },
        ),
    ]
