# Generated by Django 3.1.6 on 2021-03-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0012_remove_teamhistory_total_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamhistory',
            name='stock_size',
        ),
    ]
