# Generated by Django 3.1.6 on 2021-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0013_remove_teamhistory_stock_size'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tick',
            index=models.Index(fields=['round', 'index'], name='pastvina_ti_round_i_141cc4_idx'),
        ),
    ]
