# Generated by Django 3.1.6 on 2021-03-14 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastvina', '0015_auto_20210314_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmarkethistory',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastvina.crop', verbose_name='plodina'),
        ),
        migrations.AlterField(
            model_name='livestockmarkethistory',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastvina.livestock', verbose_name='dobytek'),
        ),
        migrations.AlterField(
            model_name='teamcropactionhistory',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastvina.crop', verbose_name='plodina'),
        ),
        migrations.AlterField(
            model_name='teamcropactionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='tým'),
        ),
        migrations.AlterField(
            model_name='teamcrophistory',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastvina.crop', verbose_name='plodina'),
        ),
        migrations.AlterField(
            model_name='teamcrophistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='tým'),
        ),
        migrations.AlterField(
            model_name='teamhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='tým'),
        ),
        migrations.AlterField(
            model_name='teamlivestockactionhistory',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastvina.livestock', verbose_name='dobytek'),
        ),
        migrations.AlterField(
            model_name='teamlivestockactionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='tým'),
        ),
        migrations.AlterField(
            model_name='teamlivestockhistory',
            name='livestock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastvina.livestock', verbose_name='dobytek'),
        ),
        migrations.AlterField(
            model_name='teamlivestockhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='tým'),
        ),
        migrations.AlterField(
            model_name='tick',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastvina.round', verbose_name='kolo'),
        ),
    ]
