# Generated by Django 3.1.6 on 2021-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0018_round_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='index'),
        ),
    ]
