# Generated by Django 3.1.6 on 2021-03-19 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0019_round_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='computed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start'),
        ),
    ]
