# Generated by Django 3.1.6 on 2021-03-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0020_tick_computed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tick',
            name='computed',
        ),
    ]
