# Generated by Django 3.1.6 on 2021-03-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastvina', '0021_remove_tick_computed'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teamcrophistory',
            index=models.Index(fields=['crop'], name='pastvina_te_crop_id_24311b_idx'),
        ),
        migrations.AddIndex(
            model_name='teamlivestockhistory',
            index=models.Index(fields=['livestock'], name='pastvina_te_livesto_4895ae_idx'),
        ),
    ]
